#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Jan 23, 2026 12:07:23 AM JST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Relative
set vTcl(mode) Relative
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 600x450+298+209
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    entry "$top.ent49" \
        -background #d9d9d9 -borderwidth 1 -cursor xterm \
        -disabledbackground #d9d9d9 -disabledforeground #a3a3a3 \
        -exportselection 0 -font "TkFixedFont" -foreground #000000 \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 1 -insertbackground #000000 -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground #d9d9d9 -relief sunken -selectbackground #d9d9d9 \
        -selectborderwidth 0 -selectforeground black -state normal \
        -validate none -width 10 
    vTcl:DefineAlias "$top.ent49" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor nw \
        -background #d9d9d9 -borderwidth 1 -compound left \
        -disabledforeground #a3a3a3 -font "TkDefaultFont" -foreground #000000 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -justify center -padx 1 -pady 1 -relief flat \
        -state normal -takefocus 0 -text "ブロガーurl:" -underline -1 -width 0 \
        -wraplength 1 
    vTcl:DefineAlias "$top.lab52" "label1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.ent49
    place $top.ent49 \
        -in $top -x 0 -relx 0.15 -y 0 -width 500 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab52
    place $top.lab52 \
        -in $top -x 0 -y 0 -width 0 -relwidth 0.2 -height 0 -relheight 0.089 \
        -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

